#This is a bed file of peaks that you are considering 
peakBedFile='/srv/scratch/annashch/stemcells/het/output/remapped_merged_peaks/all.idr.bed.merged'

#this is the counts file generated by the scrpt countsfiles_regression_pseudorep.R
countData<-data.frame(read.table('/srv/scratch/annashch/stemcells/het/pseudorep_counts.regression.csv',header=TRUE,sep=',',row.names=1)); 

padjCutoff <- 0.1 # If this is not 0.1, we have to tweak DESeq's filtering.

batchesMatrix <- matrix(
  c('M5_r4', 'B1',
    'M5_r2', 'B1', 
    'Hk_r2','B1',
    'Hk_r1','B1', 
    'CC_r2','B1',
    'CC_r1','B1',
    '3hr_r3','B1',
    '3hr_r2','B1',
    '16hr_r2','B1',
    '16hr_r1','B1',
    '16hr_r3','B1',
    '48hr_r3','B1',
    '48hr_r2','B1',
    'H1_r3','B1',
    'H1_r1','B1',
    'H1_r2','B1'),
  
  ncol = 2,
  byrow = TRUE)

conditionsToCompare <- data.frame(
  matrix(
    c('3hr', 'CC', 
      '16hr', '3hr', '16hr', 'CC',
      '48hr', '16hr', '48hr', '3hr', '48hr', 'CC',
      'H1', '48hr', 'H1', '16hr', 'H1', '3hr', 'H1', 'CC',
      'H1', 'Hk', '48hr', 'Hk', '16hr', 'Hk', '3hr', 'Hk', 
      'H1', 'M5', '48hr', 'M5', '16hr', 'M5', '3hr', 'M5'),
    ncol = 2,
    byrow = TRUE),
  stringsAsFactors = FALSE)

#output file names 
outputfname_diffmat="diffMat.csv" 
outputfname_foldchange="foldChange.csv"
outputfname_confidence="confidence.csv" 

######################################################################################
library("DESeq2")
library("RColorBrewer")
library("gplots")
library("dplyr")
library("BiocParallel")
library("ggplot2")


register(MulticoreParam(12))
parallelFlag <- TRUE
batches <- data.frame(batchesMatrix[, 2],
                      row.names = batchesMatrix[, 1])


colnames(conditionsToCompare) <- c('later', 'earlier')
conditionsToCompare <- mutate(conditionsToCompare, 
                              both = paste(later, earlier, sep = "-"))

# Read in data
experimentNames=names(countData); 
conditionNames <- data.frame(strsplit(experimentNames, '_'),
                             stringsAsFactors = FALSE)
conditionNames <- t(conditionNames[1, ])
colnames(countData) <- conditionNames

# Filter out conditions in conditionsToCompare that aren't present
conditionsToCompare <- filter(
  conditionsToCompare,
  later %in% conditionNames,
  earlier %in% conditionNames)

# Construct the colData object that DESeq needs as metadata
colData <- data.frame(condition = conditionNames, 
                      batch = batches[experimentNames, ],
                      row.names = experimentNames)

# Generate DESeq DataSet
dds <- DESeqDataSetFromMatrix(
  countData = countData,
  colData = colData,
  design = ~condition
)
dds <- DESeq(dds, parallel = parallelFlag)

# Generate differential openness matrix
# Each column is a pair of (later, earlier) conditions 
# as specified in conditionsToCompare
numCols <- nrow(conditionsToCompare)
numRows <- nrow(countData)
diffMat <- matrix(, ncol = numCols, nrow = numRows)
confidenceMatt<-matrix(,ncol=numCols, nrow=numRows)
foldChangeMat<-matrix(,ncol=numCols,nrow=numRows) 


for (i in 1:numCols){
  res <- results(dds, 
                 contrast = c("condition", 
                              conditionsToCompare[i, 'later'], 
                              conditionsToCompare[i, 'earlier']), 
                 parallel = parallelFlag)
  low_deltas=which(abs(res$log2FoldChange)<0.15)
  res$log2FoldChange[low_deltas]=0
  diffMat[, i] <- (res$padj <= padjCutoff) * sign(res$log2FoldChange)
  confidenceMatt[,i]<-res$padj
  foldChangeMat[,i]<-res$log2FoldChange
}

#summary(res)
#plotMA(res)

# Replace NAs and filter out all rows of diffMat that are all zero
# Remember to take abs so that +1s and -1s don't cancel each other out
diffMat[is.na(diffMat)] <- 0
confidenceMatt[is.na(confidenceMatt)]<-1
foldChangeMat[is.na(foldChangeMat)]<-0 
#idxToKeep <- rowSums(abs(diffMat)) > 0
#diffMat <- diffMat[idxToKeep, ]
colnames(diffMat) <- conditionsToCompare[, 'both']
colnames(confidenceMatt)<-conditionsToCompare[,'both'] 
colnames(foldChangeMat)<-conditionsToCompare[,'both'] 

peakNames <- read.table(
  sprintf("all.ppr.bed.merged"),header=TRUE,
  colClasses = c("character"))
alldata=data.frame(peakNames,as.data.frame(diffMat))
allconfidence=data.frame(peakNames,as.data.frame(confidenceMatt))
allfoldchange=data.frame(peakNames,as.data.frame(foldChangeMat))

# Write diffMat to disk
write.table(alldata,
            file = sprintf(
              outputfname_diffmat,
              padjCutoff),sep='\t')
#Write confidenceMatt to disk
write.table(allconfidence,
            file = sprintf(
              outputfname_confidence,
              padjCutoff),sep='\t')
write.table(allfoldchange,
            file = sprintf(
              outputfname_foldchange,
              padjCutoff),sep='\t')