setwd("/Users/larsgr/OneDrive - Syddansk Universitet/Seq_analysis/BMB838")

#####LOAD DATA####

RPKM <- read.delim("RPKM.txt", header=TRUE)
RPKM <- subset(RPKM, select=c(1:4,8:41))
colnames(RPKM)=c("ID",
                "chr",
                "start",
                "end",
                "gene",
                "ZT2_r1",
                "ZT2_r2",
                "ZT2_r3",
                "ZT6_r1",
                "ZT6_r2",
                "ZT6_r3",
                "ZT10_r1",
                "ZT10_r2",
                "ZT10_r3",
                "ZT13unfed_r1",
                "ZT13unfed_r2",
                "ZT13unfed_r3",
                "ZT13fed_r1",
                "ZT13fed_r2",
                "ZT13fed_r3",
                "ZT14unfed_r1",
                "ZT14unfed_r2",
                "ZT14unfed_r3",
                "ZT14fed_r1",
                "ZT14fed_r2",
                "ZT14fed_r3",
                "ZT18unfed_r1",
                "ZT18unfed_r2",
                "ZT18unfed_r3",
                "ZT18fed_r1",
                "ZT18fed_r2",
                "ZT18fed_r3",
                "ZT22unfed_r1",
                "ZT22unfed_r2",
                "ZT22unfed_r3",
                "ZT22fed_r1",
                "ZT22fed_r2",
                "ZT22fed_r3")
rownames(RPKM) <- RPKM[,1]
RPKM[,1] <- NULL
RPKM$mean_all <- rowMeans(RPKM[,5:37])
newCol1<-strsplit(as.character(RPKM$gene),'|',fixed=TRUE)
RPKM<-data.frame(RPKM,do.call(rbind, newCol1))
RPKM <- subset(RPKM, select=c(1:39))
names(RPKM)[39]<-"GENE_NAME"

RAW <- read.delim("RAW.txt", header=TRUE)
RAW <- subset(RAW, select=c(1,9:41))
colnames(RAW)=c("ID",
                 "ZT2_r1",
                 "ZT2_r2",
                 "ZT2_r3",
                 "ZT6_r1",
                 "ZT6_r2",
                 "ZT6_r3",
                 "ZT10_r1",
                 "ZT10_r2",
                 "ZT10_r3",
                 "ZT13unfed_r1",
                 "ZT13unfed_r2",
                 "ZT13unfed_r3",
                 "ZT13fed_r1",
                 "ZT13fed_r2",
                 "ZT13fed_r3",
                 "ZT14unfed_r1",
                 "ZT14unfed_r2",
                 "ZT14unfed_r3",
                 "ZT14fed_r1",
                 "ZT14fed_r2",
                 "ZT14fed_r3",
                 "ZT18unfed_r1",
                 "ZT18unfed_r2",
                 "ZT18unfed_r3",
                 "ZT18fed_r1",
                 "ZT18fed_r2",
                 "ZT18fed_r3",
                 "ZT22unfed_r1",
                 "ZT22unfed_r2",
                 "ZT22unfed_r3",
                 "ZT22fed_r1",
                 "ZT22fed_r2",
                 "ZT22fed_r3")
rownames(RAW) <- RAW[,1]
RAW[,1] <- NULL
RAW <- RAW*2

####### DESeq2 analysis ########

DESeq2 <- subset(RAW, select=c(22:27))

cts <- as.matrix(DESeq2)

#Generate data info file that should match the raw tag count file generated by HOMER
coldata = matrix(c("ZT18unfed_r1","ZT18unfed_r2","ZT18unfed_r3","ZT18fed_r1","ZT18fed_r2","ZT18fed_r3",
                   "SM4480","SM4481","SM4482","SM4483", "SM4484", "SM4485",
                   "unfed","unfed","unfed","fed","fed","fed",
                   "paired-end","paired-end","paired-end","paired-end","paired-end","paired-end"), 
                 nrow=6, 
                 ncol=4) 
rownames(coldata) <- coldata[,1]
coldata<-coldata[,-1]
colnames(coldata)=c("Sample","condition","type")

all(rownames(coldata) %in% colnames(cts)) #test if data info match data file - should be TRUE
all(rownames(coldata) == colnames(cts)) #test if data info match data file - should be TRUE

#analyse using DESeq2
library("DESeq2")
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ condition)
dds
dds <- DESeq(dds)
res <- results(dds, contrast=c("condition","fed","unfed"))
#res <- results(dds)
res
summary(res)

#make data into a data frame, set NA=1 in padj and NA=0 in log2FoldChange
DESeq_fed_vs_unfed_ZT18 <- as.data.frame(res) 
DESeq_fed_vs_unfed_ZT18$padj[is.na(DESeq_fed_vs_unfed_ZT18$padj)] <- 1 #NA=1
DESeq_fed_vs_unfed_ZT18$log2FoldChange[is.na(DESeq_fed_vs_unfed_ZT18$log2FoldChange)] <- 0 #NA=0
DESeq_fed_vs_unfed_ZT18 <- subset(DESeq_fed_vs_unfed_ZT18, select=c(1,2,6))
colnames(DESeq_fed_vs_unfed_ZT18)=c("basemean_DESeq_fed_vs_unfed_ZT18",
                                  "log2FC_DESeq_fed_vs_unfed_ZT18",
                                  "FDR_DESeq_fed_vs_unfed_ZT18")

#merge DESeq2 data with RPKM dataframe
df <- merge(RPKM, DESeq_fed_vs_unfed_ZT18, by="row.names", all=F)  # merge by row names (by=0 or by="row.names")
rownames(df) <- df[,1]
df<-df[,-1]

df <- df[!duplicated(df$GENE_NAME), ] #remove dublicate gene names

#####DATA ANALYSIS#####

#PCA plot
a=df[,c(5:38)]
a=a[a$mean_all > 100,]
a=a[,c(1:33)]
pseudoCount = log2(a+1) #tag log2 to rpkm values
PCA <- prcomp(t(pseudoCount)) #t to transpose 
head(PCA)
Components <- PCA$x
plot(Components[,1], Components[,2], pch=16, cex=1) #xlim=c(-80,80), ylim=c(-80,80)
text(Components[,1], Components[,2], labels=row.names(Components), cex= 0.7, pos=3)
PCA$sdev
PCA$sdev / sum(PCA$sdev)
100*(PCA$sdev / sum(PCA$sdev))

#volcano plot
plot(df$log2FC_DESeq_fed_vs_unfed_ZT18,-log10(df$FDR_DESeq_fed_vs_unfed_ZT18),
     xlab="log2FC", ylab="-log10 FDR",
     xlim=c(-4,4),
     #ylim=c(0,200),
     cex=0.5,
     pch=19
)

#volcano plot using ggplot
library("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
library("ggrepel", lib.loc="/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
ggplot(df, aes(x=log2FC_DESeq_fed_vs_unfed_ZT18, y=-log10(FDR_DESeq_fed_vs_unfed_ZT18))) + 
  geom_point(size=1) + 
  xlim(-4,4) +
  ylim(0,200) +
  theme_bw() +
  theme(axis.line = element_line(color = 'black'),  panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank())

df$Significant <- ifelse(df$FDR_DESeq_fed_vs_unfed_ZT18 < 0.01, "FDR < 0.01", "Not Sig")
ggplot(df, aes(x = log2FC_DESeq_fed_vs_unfed_ZT18, y = -log10(FDR_DESeq_fed_vs_unfed_ZT18))) +
  geom_point(aes(color = Significant)) +
  scale_color_manual(values = c("red", "grey")) +
  theme_bw(base_size = 12) + theme(legend.position = "bottom") +
  geom_text_repel(
    data = subset(df, FDR_DESeq_fed_vs_unfed_ZT18 < 0.00000000000000000000001),
    aes(label = GENE_NAME),
    size = 3,
    box.padding = unit(0.35, "lines"),
    point.padding = unit(0.2, "lines")
  )

# MA plot using ggplot
df$Significant <- ifelse(df$FDR_DESeq_fed_vs_unfed_ZT18 < 0.01, "FDR < 0.01", "Not Sig")
ggplot(df, aes(x = log10(basemean_DESeq_fed_vs_unfed_ZT18), y = log2FC_DESeq_fed_vs_unfed_ZT18)) +
  geom_point(aes(color = Significant)) +
  scale_color_manual(values = c("red", "grey")) +
  theme_bw(base_size = 12) + theme(legend.position = "bottom") +
  geom_text_repel(
    data = subset(df, log2FC_DESeq_fed_vs_unfed_ZT18 > 2),
    aes(label = GENE_NAME),
    size = 3,
    box.padding = unit(0.35, "lines"),
    point.padding = unit(0.1, "lines")
  )

#heatmap
df_sig <- df[df$FDR_DESeq_fed_vs_unfed_ZT18 < 0.01,]
a=subset(df_sig, select=c(29:31,26:28))
library("clusterSim", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
a_norm <- data.Normalization(a,type="n1",normalization="row")
hmcols<-colorRampPalette(c("blue","black","yellow"))(256)
library(pheatmap)
heatmap <- pheatmap(as.matrix(a_norm), kmeans_k = NA, cluster_rows=T, border_color = NA, cluster_cols = F, cutree_rows = 4, fontsize_row = 0.5, col=hmcols, clustering_method = "ward.D")

#######diurnal analysis of data using MetaCycle - RNA-seq#####
library("MetaCycle", lib.loc="~/Library/R/3.3/library")
library("clusterSim", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")

#generate dataframe for analysis
df_cir <- df #df[df$FDR_DESeq_fed_vs_unfed_ZT18 < 0.01,]
a=subset(df_cir, select=c(5:13,23:25,29:31,35:37))
colnames(a)=c("2","2","2","6","6","6","10","10","10","14","14","14","18","18","18","22","22","22")
write.table(a, file="circadian_df.txt", sep="\t", col.names=NA) #export clusters

#analyze with JTK_CYCLE and Lomb-Scargle
#meta2d(infile="circadian_df.txt", filestyle="txt",
#       outdir="circ_Diurnal_RNAseq", timepoints="Line1")

#input circadian data into R
meta2d <- read.delim("circ_Diurnal_RNAseq/meta2d_circadian_df.txt", header=TRUE)
rownames(meta2d) <- meta2d[,1]
meta2d[,1] <- NULL

#merge meta2d with dataframe
df <- merge(df, meta2d, by="row.names", all=F)  # merge by row names (by=0 or by="row.names")
rownames(df) <- df[,1]
df<-df[,-1]
df <- df[order(df$JTK_adjphase),]

#mean of each timepoint
df$ZT2 <- rowMeans(df[,5:7])
df$ZT6 <- rowMeans(df[,8:10])
df$ZT10 <- rowMeans(df[,11:13])
df$ZT13f <- rowMeans(df[,17:19])
df$ZT14f <- rowMeans(df[,23:25])
df$ZT18f <- rowMeans(df[,29:31])
df$ZT22f <- rowMeans(df[,35:37])
df$ZT13u <- rowMeans(df[,14:16])
df$ZT14u <- rowMeans(df[,20:22])
df$ZT8u <- rowMeans(df[,26:28])
df$Z22u <- rowMeans(df[,32:34])


#plot as heatmap
cir <- df[df$JTK_pvalue <0.01,]
a=subset(cir, select=c(5:13,23:25,29:31,35:37))
library("clusterSim", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
a_norm <- data.Normalization(a,type="n1",normalization="row")
hmcols<-colorRampPalette(c("blue","black","yellow"))(256)
library(pheatmap)
heatmap <- pheatmap(as.matrix(a_norm), kmeans_k = NA, cluster_rows=F, border_color = NA, cluster_cols = F, cutree_rows = 4, fontsize_row = 0.5, col=hmcols, clustering_method = "ward.D")

a=subset(cir, select=c(5:13,20:22,26:28,32:34))
library("clusterSim", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
a_norm <- data.Normalization(a,type="n1",normalization="row")
hmcols<-colorRampPalette(c("blue","black","yellow"))(256)
library(pheatmap)
heatmap <- pheatmap(as.matrix(a_norm), kmeans_k = NA, cluster_rows=F, border_color = NA, cluster_cols = F, cutree_rows = 4, fontsize_row = 0.5, col=hmcols, clustering_method = "ward.D")

#plot as heatmap
a=subset(cir, select=c(61:63,65:67,69:71))
library("clusterSim", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
a_norm <- data.Normalization(a,type="n1",normalization="row")
hmcols<-colorRampPalette(c("blue","black","yellow"))(256)
library(pheatmap)
heatmap <- pheatmap(as.matrix(a_norm), kmeans_k = NA, cluster_rows=F, border_color = NA, cluster_cols = F, cutree_rows = 4, fontsize_row = 0.5, col=hmcols, clustering_method = "ward.D")

#####EXPORT DATA####
write.table(df, file="df_export.txt", sep="\t", col.names=NA) #export clusters



